version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - backend
    expose:
      - 5432
    ports:
      - 5432:5432

  bastet:
    container_name: bastet
    restart: on-failure
    tty: true
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_started
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    volumes:
      - ./:/app
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    driver: bridge
