name: Validate

on:
  pull_request:
    branches:
      - main

jobs:

  validate:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4

    - name: Format
      run: make tidy

    - name: Check
      run: make check

    - name: Test
      run: make test
